{{ with .Values.policyException }}
{{ if .enabled }}
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: {{ $.Release.Namespace }}-{{$.Release.Name}}-kb
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  exceptions:
    - policyName: disallow-capabilities-strict
      ruleNames:
        - require-drop-all
    - policyName: disallow-privilege-escalation
      ruleNames:
        - privilege-escalation
    - policyName: require-run-as-nonroot
      ruleNames:
        - run-as-non-root
    - policyName: restrict-seccomp-strict
      ruleNames:
        - check-seccomp-strict
  match:
    any:
      - resources:
          kinds:
            - Pod
          names:
            - {{ $.Release.Name }}-kb-*
          namespaces:
            - {{ $.Release.Namespace }}
{{- end }}
{{- end }}
